/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CredibilitySection: typeof import('./src/components/home/CredibilitySection.vue')['default']
    CTASection: typeof import('./src/components/home/CTASection.vue')['default']
    FooterSection: typeof import('./src/components/layout/FooterSection.vue')['default']
    HeaderNav: typeof import('./src/components/layout/HeaderNav.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesOverview: typeof import('./src/components/home/ServicesOverview.vue')['default']
    TestimonialsSection: typeof import('./src/components/home/TestimonialsSection.vue')['default']
  }
}
