name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Check for outdated packages
        id: outdated
        run: |
          echo "Checking for outdated packages..."
          npm outdated --json > outdated.json || true
          cat outdated.json
          
      - name: Update dependencies
        run: |
          # Update all dependencies to latest minor/patch versions
          npm update --save
          
          # Check if package-lock.json changed
          if git diff --exit-code package-lock.json; then
            echo "No updates available"
            echo "updates_available=false" >> $GITHUB_OUTPUT
          else
            echo "Updates available"
            echo "updates_available=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Run tests after update
        if: steps.outdated.outputs.updates_available == 'true'
        run: |
          npm ci
          npm run lint
          npm run test:run
          npm run build
          
      - name: Create Pull Request
        if: steps.outdated.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update npm dependencies'
          title: 'Weekly Dependency Updates'
          body: |
            ## Automated Dependency Update
            
            This PR contains automated dependency updates for the week.
            
            ### Changes
            - Updated npm dependencies to their latest compatible versions
            - All tests have been run and passed
            - Build process completed successfully
            
            ### Review Checklist
            - [ ] Review dependency changes in package-lock.json
            - [ ] Check for any breaking changes in updated packages
            - [ ] Verify application still works as expected
            - [ ] Review security advisories if any
            
            ---
            *This PR was automatically created by the dependency update workflow.*
          branch: automated-dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
          assignees: |
            ${{ github.actor }}
          reviewers: |
            ${{ github.actor }}